# 월별 평가


1. 레코드를 모두다 기록하세요 (30 점)

2. 전역 컨텍스트 이후의 실행 컨텍스트의 변화를 모두 작성하세요(console.log()는 컨텍스트 설명 제외 가능) (40 점)

3. 코드의 내용을 모두 실행 순서에 맞게 출력을 작성하세요 (30 점)
   (코드의 에러 내용의 함정도 왜 발생하는지 작성해야 한다. 이유 작성)


## 문제 1
> 자료구조 스택과 큐에 대해 설명해주세요.(서술형)

- 자료구조 스택은 쌓아올린 데이터가 늦게 들어온 순서대로 빠지는 후입선출 형태이다.
- 자료구조 큐는 쌓아올린 데이터가 빨리 들어온 순서대로 빠지는 선입선출 형태이다.

## 문제 2
```js

function foo() {
    const num = 1;
    function foo2() {
        console.log(num);              // 오류
        const num = 2;
        function foo3() {
            const num = 3;
            console.log(num);
        }

        function foo4(num) {
            console.log(num);            
        }
        foo4(num);
    }
    foo2();
}

foo();
// 1.foo 라는 전역 컨텍스트가 생성되고

// 2.foo 함수를 실행하고 foo 실행 컨텍스트가 생성된다

// 3.foo라는 실행 컨텍스트 안에 const num, function foo2()가 생성이 되고 foo2() 함수를 실행한다.
// (foo 생성 컨텍스트:const num,function bar2)  (foo 실행 컨텍스트:const num = 1, foo2())

// 4.foo2라는 컨텍스트가 생성이 되고 foo2라는 실행컨텍스트 안에 const num이 생성이되고

// 5.console.log(num);을 실행을 하는데 const num의 값이 선언되기 전에 console.log(num);을 실행하기 때문에
// (foo2 생성컨텍스트:const num,function foo3(),function foo4(num)) (foo2 실행컨텍스트:const num = 2, foo4(num))

// 6.오류가 뜨면서 결과적으로 아무값도 출력되지 않는다.

```

## 문제 3
```js

function boo() {
    function boo2() {
        console.log(num);
        const num = 2;
    }
    
    const num = 1;
    boo2();
    boo3();
    function boo3() {
        console.log(num)
    }
}                                                   // 오류


// 1.boo라는 전역 컨텍스트가 생성이 되고
// 2.boo를 실행시킬 컨텍스트가 없어서 오류가 난다.
```



## 문제 4

```js

function bar() {
    const num = 1;
    function bar2() {
        console.log(num);               // 오류
        const num = 2;
        function bar3() {
            const num = 3;
            console.log(num);
        }

        function bar4(num) {
            console.log(num);             
        }
        bar4(num);
    }
    bar2();
}                                     

bar(); 

// 1.bar 라는 전역 컨텍스트가 생성되고

// 2.bar 함수를 실행하고 bar 실행 컨텍스트가 생성된다

// 3.bar라는 실행 컨텍스트 안에 const num, function bar2()가 생성이 되고 bar 2() 함수를 실행한다.
// (bar 생성 컨텍스트:const num,function bar2)  (bar 실행 컨텍스트:const num = 1, bar2())

// 4.bar2라는 컨텍스트가 생성이 되고 bar2라는 실행컨텍스트 안에 const num이 생성이되고

// 5.console.log(num);을 실행을 하는데 const num의 값이 선언되기 전에 console.log(num);을 실행하기 때문에
// (bar2 생성컨텍스트:const num,function bar3(),function bar4(num)) (bar2 실행컨텍스트:const num = 2, bar4(num))

// 6.오류가 뜨면서 결과적으로 아무값도 출력되지 않는다.


```

## 문제 5

```js

function bar() {
    function bar2() {
        const num = 1
        console.log(num);          // 1
        if(true) {
            console.log(num);      // 오류      
            const num = 2;
        }
        function bar3() {
            console.log(num);
        }

        function bar4(num) {
            console.log(num);  
        }
        bar4(num);
    }
    bar2();                            
}

bar(); 

// 1.bar 라는 전역 컨텍스트가 생성되고

// 2.bar 함수를 실행하고 bar 실행 컨텍스트가 생성된다

// 3.bar라는 실행 컨텍스트 안에 function bar2()가 생성이 되고 bar2() 함수를 실행한다
// (bar 생성 컨텍스트:function bar2)  (bar 실행 컨텍스트:bar2())

// 4.bar2()라는 컨텍스트가 생성되고 bar2() 컨텍스트 안에 const num, if(true), function bar3(),  function bar4가 생성이 되고
// (bar 생성 컨텍스트:const num, if(true), function bar3(), function bar4 )  (bar 실행 컨텍스트:const num = 1, bar4(num))

// 5.const num = 1로 선언을 하고 bar2 안에 있는 console.log(num); 을 출력하면 num=1로 초기화 된 상태기 때문에 1이 출력된다.

// 6.그 이후 if(true)를 실행하면 if 컨텍스트 안에 const num이 생성이 되고 console.log(num);을 실행하는데 const num의 값이 선언되기 전에 console.log(num);을 실행하기 때문에 아무값도 뜨지않고 오류가 뜨게 된다
// (if(true)생성 컨텍스트:const num)

// 7. 결과적으로 1이 먼저 출력되고 그 이후에는 레퍼런스 오류로 인해 값이 출력되지 않는다.
```